spring.application.name=backend-atlas

# DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/atlas
spring.datasource.username=postgres
spring.datasource.password=password
