spring.application.name=backend-atlas

# DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/atlas
spring.datasource.username=postgres
spring.datasource.password=password

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ACTUATORS
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always