spring.application.name=backend-atlas

# DB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/atlas
spring.datasource.username=postgres
spring.datasource.password=password

# LOGGING
logging.level.root=INFO
logging.level.com.example=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.file.name=logs/application.log

# REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

# RABITMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# ACTUATORS
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always